name: Daily Commit Job

on:
  schedule:
    - cron: '30 9 * * *' # runs daily at 9:30 UTC
  workflow_dispatch:

jobs:
  daily_commit_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Daily commit by 23f2002790@ds.study.iitm.ac.in
        run: |
          echo "Daily update: $(date -u)" >> daily-log.txt
          git config user.name "GitHub Actions Bot"
          git config user.email "23f2002790@ds.study.iitm.ac.in"
          git add daily-log.txt
          git commit -m "Automated update: $(date -u)" || echo "No changes to commit"
          git push
