name: Dependency Cache Example

on:
  push:
    branches:
      - main
  workflow_dispatch: # manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python (or your environment)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Step 3: Cache dependencies
      - name: Cache pip dependencies
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-02984c9
          restore-keys: |
            cache-02984c9

      # Step 4: Prime cache (check if hit/miss)
      - name: prime-cache-02984c9
        run: |
          if [ "${{ steps.cache-deps.outputs.cache-hit }}" == "true" ]; then
            echo "Cache hit!"
          else
            echo "Cache miss!"
          fi

      # Step 5: Install dependencies
      - name: Install dependencies
        run: |
          pip install requests
