name: Dependency Cache Example

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Cache dependencies with ID
      - name: Cache pip dependencies
        id: cache-deps    # <- ID is used for output reference
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-02984c9
          restore-keys: |
            cache-02984c9

      # Prime cache step
      - name: prime-cache-02984c9
        run: |
          if [ "${{ steps.cache-deps.outputs.cache-hit }}" == "true" ]; then
            echo "Cache hit!"
          else
            echo "Cache miss!"
          fi

      - name: Install dependencies
        run: pip install requests
