name: Email Step Action

on:
  push:
    branches:
      - main   # or any branch you want to trigger the workflow

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: 23f2002790@ds.study.iitm.ac.in
        run: echo "Hello, world!"
